//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendances
    {
        public int AttendanceID { get; set; }
        public int ClientID { get; set; }
        public int ScheduleID { get; set; }
        public bool IsPresent { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Schedules Schedules { get; set; }
    }
}
