//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.Attendances = new HashSet<Attendances>();
            this.Contracts = new HashSet<Contracts>();
            this.Messages = new HashSet<Messages>();
            this.Groups = new HashSet<Groups>();
        }
    
        public int ClientID { get; set; }
        public int UserID { get; set; }
        public string AdditionalInfo { get; set; }
    
        public virtual ICollection<Attendances> Attendances { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Contracts> Contracts { get; set; }
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
