//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Feedbacks
    {
        public int FeedbackID { get; set; }
        public System.DateTime FeedbackDate { get; set; }
        public string Content { get; set; }
        public int UserID { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
