//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Homeworks
    {
        public Homeworks()
        {
            this.HomeworkFiles = new HashSet<HomeworkFiles>();
            this.Groups = new HashSet<Groups>();
        }
    
        public int HomeworkID { get; set; }
        public int ScheduleID { get; set; }
        public string Description { get; set; }
        public System.DateTime Deadline { get; set; }
    
        public virtual ICollection<HomeworkFiles> HomeworkFiles { get; set; }
        public virtual Schedules Schedules { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
