//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public Languages()
        {
            this.Groups = new HashSet<Groups>();
            this.Services = new HashSet<Services>();
        }
    
        public int LanguageID { get; set; }
        public string LanguageName { get; set; }
    
        public virtual ICollection<Groups> Groups { get; set; }
        public virtual ICollection<Services> Services { get; set; }
    }
}
