//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int MessageID { get; set; }
        public int ClientID { get; set; }
        public int TeacherID { get; set; }
        public string MessageText { get; set; }
        public System.DateTime SentDate { get; set; }
        public bool IsRead { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
