//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Teachers
    {
        public Teachers()
        {
            this.Messages = new HashSet<Messages>();
            this.Schedules = new HashSet<Schedules>();
            this.Groups = new HashSet<Groups>();
        }
    
        public int TeacherID { get; set; }
        public int UserID { get; set; }
        public string Specialization { get; set; }
    
        public virtual ICollection<Messages> Messages { get; set; }
        public virtual ICollection<Schedules> Schedules { get; set; }
        public virtual Users Users { get; set; }
        public virtual ICollection<Groups> Groups { get; set; }
    }
}
