//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LanguageSchool.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.Clients = new HashSet<Clients>();
            this.Feedbacks = new HashSet<Feedbacks>();
            this.Teachers = new HashSet<Teachers>();
        }
    
        public int UserID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Gender { get; set; }
        public byte[] Photo { get; set; }
        public string Password { get; set; }
        public int RoleID { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual ICollection<Feedbacks> Feedbacks { get; set; }
        public virtual Roles Roles { get; set; }
        public virtual ICollection<Teachers> Teachers { get; set; }
    }
}
